name: my_time_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  flutter:
    sdk: flutter
  http: ^0.12.1
  flutter_spinkit: ^4.1.1+1
  google_fonts: ^1.1.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/egypt.png